In [61]:
import numpy as np
from scipy.signal import savgol_filter

In [62]:
def SmoothRaman(file_path):
    data = np.loadtxt(file_path)
    raman_shift = data[:,0]
    intensity = data[:,2] #change this value based on what plot you want to extract
    intensity_smoothed = savgol_filter(intensity, window_length=11, polyorder=3) #adjust polyorder as needed
    np.savetxt('smoothed_data.txt', np.column_stack((raman_shift, intensity_smoothed)), fmt='%.6f')
    return raman_shift, intensity_smoothed, intensity

In [63]:
file_path = "path/to/file"
SmoothRaman(file_path)

(array([1000.17, 1000.63, 1001.1 , ..., 2998.98, 2999.32, 2999.67]),
 array([23.39160839, 21.25874126, 20.80652681, ..., 26.70862471,
        24.52447552, 21.61538462]),
 array([23., 22., 22., ..., 25., 27., 21.]))